// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May  5 2026 15:32:23 IST (May  5 2026 10:02:23 UTC)

// Verification Directory fv/spi_slave_memory 

module spi_slave_memory(SCLK, CS, MOSI, RST_N, MISO, REG0_OUT,
     REG1_OUT, REG2_OUT, REG3_OUT, REG4_OUT);
  input SCLK, CS, MOSI, RST_N;
  output MISO;
  output [7:0] REG0_OUT, REG1_OUT, REG2_OUT, REG3_OUT, REG4_OUT;
  wire SCLK, CS, MOSI, RST_N;
  wire MISO;
  wire [7:0] REG0_OUT, REG1_OUT, REG2_OUT, REG3_OUT, REG4_OUT;
  wire [15:0] shift_reg;
  wire [7:0] tx_buffer;
  wire [4:0] bit_count;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_84;
  EDFCNQD1BWP7T \reg_file_reg[0][3] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[2]), .E (n_79), .Q (REG0_OUT[3]));
  EDFCNQD1BWP7T \reg_file_reg[0][2] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[1]), .E (n_79), .Q (REG0_OUT[2]));
  EDFCNQD1BWP7T \reg_file_reg[0][1] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[0]), .E (n_79), .Q (REG0_OUT[1]));
  EDFCNQD1BWP7T \reg_file_reg[0][4] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[3]), .E (n_79), .Q (REG0_OUT[4]));
  EDFCNQD1BWP7T \reg_file_reg[0][7] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[6]), .E (n_79), .Q (REG0_OUT[7]));
  EDFCNQD1BWP7T \reg_file_reg[0][6] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[5]), .E (n_79), .Q (REG0_OUT[6]));
  EDFCNQD1BWP7T \reg_file_reg[0][5] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[4]), .E (n_79), .Q (REG0_OUT[5]));
  EDFCNQD1BWP7T \reg_file_reg[0][0] (.CDN (RST_N), .CP (SCLK), .D
       (MOSI), .E (n_79), .Q (REG0_OUT[0]));
  EDFCNQD1BWP7T \reg_file_reg[3][7] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[6]), .E (n_78), .Q (REG3_OUT[7]));
  EDFCNQD1BWP7T \reg_file_reg[3][6] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[5]), .E (n_78), .Q (REG3_OUT[6]));
  EDFCNQD1BWP7T \reg_file_reg[3][4] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[3]), .E (n_78), .Q (REG3_OUT[4]));
  EDFCNQD1BWP7T \reg_file_reg[3][5] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[4]), .E (n_78), .Q (REG3_OUT[5]));
  SDFCNQD1BWP7T \reg_file_reg[2][7] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[6]), .SI (REG2_OUT[7]), .SE (n_77), .Q (REG2_OUT[7]));
  SDFCNQD1BWP7T \reg_file_reg[2][5] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[4]), .SI (REG2_OUT[5]), .SE (n_77), .Q (REG2_OUT[5]));
  SDFCNQD1BWP7T \reg_file_reg[2][1] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[0]), .SI (REG2_OUT[1]), .SE (n_77), .Q (REG2_OUT[1]));
  SDFCNQD1BWP7T \reg_file_reg[2][2] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[1]), .SI (REG2_OUT[2]), .SE (n_77), .Q (REG2_OUT[2]));
  SDFCNQD1BWP7T \reg_file_reg[2][4] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[3]), .SI (REG2_OUT[4]), .SE (n_77), .Q (REG2_OUT[4]));
  SDFCNQD1BWP7T \reg_file_reg[2][6] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[5]), .SI (REG2_OUT[6]), .SE (n_77), .Q (REG2_OUT[6]));
  SDFCNQD1BWP7T \reg_file_reg[2][0] (.CDN (RST_N), .CP (SCLK), .D
       (MOSI), .SI (REG2_OUT[0]), .SE (n_77), .Q (REG2_OUT[0]));
  SDFCNQD1BWP7T \reg_file_reg[2][3] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[2]), .SI (REG2_OUT[3]), .SE (n_77), .Q (REG2_OUT[3]));
  EDFCNQD1BWP7T \reg_file_reg[1][6] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[5]), .E (n_76), .Q (REG1_OUT[6]));
  EDFCNQD1BWP7T \reg_file_reg[1][2] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[1]), .E (n_76), .Q (REG1_OUT[2]));
  EDFCNQD1BWP7T \reg_file_reg[1][3] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[2]), .E (n_76), .Q (REG1_OUT[3]));
  EDFCNQD1BWP7T \reg_file_reg[1][0] (.CDN (RST_N), .CP (SCLK), .D
       (MOSI), .E (n_76), .Q (REG1_OUT[0]));
  EDFCNQD1BWP7T \reg_file_reg[1][7] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[6]), .E (n_76), .Q (REG1_OUT[7]));
  EDFCNQD1BWP7T \reg_file_reg[1][4] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[3]), .E (n_76), .Q (REG1_OUT[4]));
  EDFCNQD1BWP7T \reg_file_reg[1][1] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[0]), .E (n_76), .Q (REG1_OUT[1]));
  EDFCNQD1BWP7T \reg_file_reg[1][5] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[4]), .E (n_76), .Q (REG1_OUT[5]));
  EDFCNQD1BWP7T \reg_file_reg[3][0] (.CDN (RST_N), .CP (SCLK), .D
       (MOSI), .E (n_78), .Q (REG3_OUT[0]));
  EDFCNQD1BWP7T \reg_file_reg[3][1] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[0]), .E (n_78), .Q (REG3_OUT[1]));
  EDFCNQD1BWP7T \reg_file_reg[3][2] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[1]), .E (n_78), .Q (REG3_OUT[2]));
  EDFCNQD1BWP7T \reg_file_reg[3][3] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[2]), .E (n_78), .Q (REG3_OUT[3]));
  DFCNQD1BWP7T \tx_buffer_reg[0] (.CDN (RST_N), .CP (SCLK), .D (n_73),
       .Q (tx_buffer[0]));
  DFCNQD1BWP7T \tx_buffer_reg[4] (.CDN (RST_N), .CP (SCLK), .D (n_75),
       .Q (tx_buffer[4]));
  DFCNQD1BWP7T \tx_buffer_reg[5] (.CDN (RST_N), .CP (SCLK), .D (n_68),
       .Q (tx_buffer[5]));
  DFCNQD1BWP7T \tx_buffer_reg[2] (.CDN (RST_N), .CP (SCLK), .D (n_71),
       .Q (tx_buffer[2]));
  DFCNQD1BWP7T \tx_buffer_reg[1] (.CDN (RST_N), .CP (SCLK), .D (n_69),
       .Q (tx_buffer[1]));
  DFCNQD1BWP7T \tx_buffer_reg[3] (.CDN (RST_N), .CP (SCLK), .D (n_70),
       .Q (tx_buffer[3]));
  DFCNQD1BWP7T \tx_buffer_reg[6] (.CDN (RST_N), .CP (SCLK), .D (n_66),
       .Q (tx_buffer[6]));
  DFCNQD1BWP7T \tx_buffer_reg[7] (.CDN (RST_N), .CP (SCLK), .D (n_67),
       .Q (tx_buffer[7]));
  ND4D0BWP7T g3380__2398(.A1 (n_61), .A2 (n_41), .A3 (n_28), .A4
       (n_72), .ZN (n_75));
  EDFCNQD1BWP7T \reg_file_reg[4][0] (.CDN (RST_N), .CP (SCLK), .D
       (MOSI), .E (n_74), .Q (REG4_OUT[0]));
  EDFCNQD1BWP7T \reg_file_reg[4][2] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[1]), .E (n_74), .Q (REG4_OUT[2]));
  EDFCNQD1BWP7T \reg_file_reg[4][1] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[0]), .E (n_74), .Q (REG4_OUT[1]));
  EDFCNQD1BWP7T \reg_file_reg[4][3] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[2]), .E (n_74), .Q (REG4_OUT[3]));
  ND4D0BWP7T g3377__5107(.A1 (n_62), .A2 (n_38), .A3 (n_36), .A4
       (n_72), .ZN (n_73));
  EDFCNQD1BWP7T \reg_file_reg[4][4] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[3]), .E (n_74), .Q (REG4_OUT[4]));
  EDFCNQD1BWP7T \reg_file_reg[4][6] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[5]), .E (n_74), .Q (REG4_OUT[6]));
  EDFCNQD1BWP7T \reg_file_reg[4][7] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[6]), .E (n_74), .Q (REG4_OUT[7]));
  EDFCNQD1BWP7T \reg_file_reg[4][5] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[4]), .E (n_74), .Q (REG4_OUT[5]));
  NR2XD0BWP7T g3387__6260(.A1 (n_64), .A2 (shift_reg[8]), .ZN (n_79));
  ND4D0BWP7T g3382__4319(.A1 (n_55), .A2 (n_45), .A3 (n_29), .A4
       (n_72), .ZN (n_71));
  ND4D0BWP7T g3381__8428(.A1 (n_46), .A2 (n_44), .A3 (n_33), .A4
       (n_72), .ZN (n_70));
  ND4D0BWP7T g3379__5526(.A1 (n_47), .A2 (n_43), .A3 (n_30), .A4
       (n_72), .ZN (n_69));
  ND4D0BWP7T g3383__6783(.A1 (n_53), .A2 (n_57), .A3 (n_35), .A4
       (n_72), .ZN (n_68));
  ND4D0BWP7T g3384__3680(.A1 (n_50), .A2 (n_48), .A3 (n_31), .A4
       (n_72), .ZN (n_67));
  ND4D0BWP7T g3376__1617(.A1 (n_51), .A2 (n_39), .A3 (n_37), .A4
       (n_72), .ZN (n_66));
  ND2D1BWP7T g3386__2802(.A1 (n_63), .A2 (shift_reg[8]), .ZN (n_77));
  INR2XD0BWP7T g3389__1705(.A1 (shift_reg[8]), .B1 (n_65), .ZN (n_78));
  NR2XD0BWP7T g3385__5122(.A1 (n_65), .A2 (shift_reg[8]), .ZN (n_76));
  DFNCND1BWP7T miso_reg(.CDN (RST_N), .CPN (SCLK), .D (n_84), .Q
       (MISO), .QN (UNCONNECTED));
  INVD0BWP7T g3392(.I (n_63), .ZN (n_64));
  AOI222D0BWP7T g3396__8246(.A1 (n_56), .A2 (REG1_OUT[0]), .B1 (n_60),
       .B2 (REG0_OUT[0]), .C1 (n_59), .C2 (REG3_OUT[0]), .ZN (n_62));
  AOI222D0BWP7T g3402__7098(.A1 (n_60), .A2 (REG0_OUT[4]), .B1 (n_59),
       .B2 (REG3_OUT[4]), .C1 (n_54), .C2 (tx_buffer[4]), .ZN (n_61));
  ND2D1BWP7T g3391__6131(.A1 (n_58), .A2 (shift_reg[7]), .ZN (n_65));
  INR2XD0BWP7T g3393__1881(.A1 (n_58), .B1 (shift_reg[7]), .ZN (n_63));
  AOI22D0BWP7T g3412__5115(.A1 (n_56), .A2 (REG1_OUT[5]), .B1 (n_59),
       .B2 (REG3_OUT[5]), .ZN (n_57));
  AOI222D0BWP7T g3401__7482(.A1 (n_52), .A2 (REG4_OUT[2]), .B1 (n_60),
       .B2 (REG0_OUT[2]), .C1 (n_54), .C2 (tx_buffer[2]), .ZN (n_55));
  AOI222D0BWP7T g3403__4733(.A1 (n_49), .A2 (REG2_OUT[5]), .B1 (n_52),
       .B2 (REG4_OUT[5]), .C1 (n_54), .C2 (tx_buffer[5]), .ZN (n_53));
  AOI222D0BWP7T g3404__6161(.A1 (n_56), .A2 (REG1_OUT[6]), .B1 (n_52),
       .B2 (REG4_OUT[6]), .C1 (n_54), .C2 (tx_buffer[6]), .ZN (n_51));
  AOI222D0BWP7T g3405__9315(.A1 (n_49), .A2 (REG2_OUT[7]), .B1 (n_56),
       .B2 (REG1_OUT[7]), .C1 (n_60), .C2 (REG0_OUT[7]), .ZN (n_50));
  AOI22D0BWP7T g3406__9945(.A1 (n_59), .A2 (REG3_OUT[7]), .B1 (n_54),
       .B2 (tx_buffer[7]), .ZN (n_48));
  AOI222D0BWP7T g3400__2883(.A1 (n_60), .A2 (REG0_OUT[1]), .B1 (n_56),
       .B2 (REG1_OUT[1]), .C1 (n_52), .C2 (REG4_OUT[1]), .ZN (n_47));
  AOI222D0BWP7T g3395__2346(.A1 (n_56), .A2 (REG1_OUT[3]), .B1 (n_49),
       .B2 (REG2_OUT[3]), .C1 (n_52), .C2 (REG4_OUT[3]), .ZN (n_46));
  AOI22D0BWP7T g3414__1666(.A1 (n_49), .A2 (REG2_OUT[2]), .B1 (n_59),
       .B2 (REG3_OUT[2]), .ZN (n_45));
  AOI22D0BWP7T g3415__7410(.A1 (n_59), .A2 (REG3_OUT[3]), .B1 (n_54),
       .B2 (tx_buffer[3]), .ZN (n_44));
  AOI22D0BWP7T g3413__6417(.A1 (n_59), .A2 (REG3_OUT[1]), .B1 (n_54),
       .B2 (tx_buffer[1]), .ZN (n_43));
  DFCND0BWP7T \bit_count_reg[3] (.CDN (n_32), .CP (SCLK), .D (n_34), .Q
       (n_16), .QN (bit_count[3]));
  INR4D0BWP7T g3390__2398(.A1 (shift_reg[9]), .B1 (shift_reg[7]), .B2
       (shift_reg[8]), .B3 (n_40), .ZN (n_74));
  AOI22D0BWP7T g3416__5107(.A1 (n_49), .A2 (REG2_OUT[4]), .B1 (n_56),
       .B2 (REG1_OUT[4]), .ZN (n_41));
  NR2XD0BWP7T g3397__6260(.A1 (n_40), .A2 (shift_reg[9]), .ZN (n_58));
  AOI22D0BWP7T g3417__4319(.A1 (n_60), .A2 (REG0_OUT[6]), .B1 (n_49),
       .B2 (REG2_OUT[6]), .ZN (n_39));
  AOI22D0BWP7T g3418__8428(.A1 (n_52), .A2 (REG4_OUT[0]), .B1 (n_54),
       .B2 (tx_buffer[0]), .ZN (n_38));
  ND2D0BWP7T g3421__5526(.A1 (n_59), .A2 (REG3_OUT[6]), .ZN (n_37));
  ND2D0BWP7T g3419__6783(.A1 (n_49), .A2 (REG2_OUT[0]), .ZN (n_36));
  ND2D0BWP7T g3420__3680(.A1 (n_60), .A2 (REG0_OUT[5]), .ZN (n_35));
  OAI22D0BWP7T g3408__1617(.A1 (n_22), .A2 (bit_count[4]), .B1 (n_17),
       .B2 (bit_count[3]), .ZN (n_34));
  ND2D0BWP7T g3422__2802(.A1 (n_60), .A2 (REG0_OUT[3]), .ZN (n_33));
  ND2D0BWP7T g3427__1705(.A1 (n_52), .A2 (REG4_OUT[7]), .ZN (n_31));
  ND2D0BWP7T g3426__5122(.A1 (n_49), .A2 (REG2_OUT[1]), .ZN (n_30));
  ND2D0BWP7T g3425__8246(.A1 (n_56), .A2 (REG1_OUT[2]), .ZN (n_29));
  ND2D0BWP7T g3428__7098(.A1 (n_52), .A2 (REG4_OUT[4]), .ZN (n_28));
  AOI31D0BWP7T g3394__6131(.A1 (n_12), .A2 (n_9), .A3 (tx_buffer[1]),
       .B (n_25), .ZN (n_27));
  IND4D0BWP7T g3409__1881(.A1 (shift_reg[13]), .B1 (n_20), .B2 (n_6),
       .B3 (n_23), .ZN (n_40));
  OAI31D0BWP7T g3410__5115(.A1 (shift_reg[4]), .A2 (shift_reg[5]), .A3
       (n_15), .B (n_26), .ZN (n_72));
  AN3D1BWP7T g3431__7482(.A1 (n_26), .A2 (shift_reg[0]), .A3 (MOSI), .Z
       (n_59));
  OAI31D0BWP7T g3407__4733(.A1 (bit_count[1]), .A2 (n_4), .A3 (n_7), .B
       (n_18), .ZN (n_25));
  OR2D1BWP7T g3424__6161(.A1 (n_23), .A2 (bit_count[4]), .Z (n_24));
  NR2XD0BWP7T g3430__9315(.A1 (n_54), .A2 (n_0), .ZN (n_52));
  NR3D0BWP7T g3432__9945(.A1 (n_54), .A2 (n_14), .A3 (shift_reg[1]),
       .ZN (n_60));
  NR3D0BWP7T g3434__2883(.A1 (n_54), .A2 (n_3), .A3 (MOSI), .ZN (n_49));
  NR3D0BWP7T g3435__2346(.A1 (n_54), .A2 (shift_reg[0]), .A3 (n_2), .ZN
       (n_56));
  INVD0BWP7T g3445(.I (n_54), .ZN (n_26));
  OAI21D0BWP7T g3447__1666(.A1 (n_19), .A2 (n_16), .B (n_21), .ZN
       (n_22));
  SDFCNQD1BWP7T \bit_count_reg[2] (.CDN (n_32), .CP (SCLK), .D (n_11),
       .SI (bit_count[2]), .SE (bit_count[4]), .Q (bit_count[2]));
  CKND1BWP7T g3457(.I (n_21), .ZN (n_23));
  IND4D0BWP7T g3455__7410(.A1 (shift_reg[6]), .B1 (bit_count[3]), .B2
       (n_20), .B3 (n_19), .ZN (n_54));
  MAOI22D0BWP7T g3429__6417(.A1 (n_19), .A2 (tx_buffer[0]), .B1 (n_13),
       .B2 (bit_count[2]), .ZN (n_18));
  EDFCNQD1BWP7T \bit_count_reg[1] (.CDN (n_32), .CP (SCLK), .D (n_8),
       .E (n_17), .Q (bit_count[1]));
  ND2D1BWP7T g3459__5477(.A1 (n_19), .A2 (n_16), .ZN (n_21));
  EDFCNQD1BWP7T \shift_reg_reg[14] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[13]), .E (n_20), .Q (shift_reg[14]));
  AO211D0BWP7T g3448__2398(.A1 (n_14), .A2 (shift_reg[1]), .B
       (shift_reg[2]), .C (shift_reg[3]), .Z (n_15));
  EDFCNQD1BWP7T \shift_reg_reg[11] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[10]), .E (n_20), .Q (shift_reg[11]));
  EDFCNQD1BWP7T \shift_reg_reg[10] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[9]), .E (n_20), .Q (shift_reg[10]));
  EDFCNQD1BWP7T \shift_reg_reg[2] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[1]), .E (n_20), .Q (shift_reg[2]));
  EDFCNQD1BWP7T \shift_reg_reg[5] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[4]), .E (n_20), .Q (shift_reg[5]));
  EDFCNQD1BWP7T \shift_reg_reg[4] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[3]), .E (n_20), .Q (shift_reg[4]));
  EDFCNQD1BWP7T \shift_reg_reg[13] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[12]), .E (n_20), .Q (shift_reg[13]));
  EDFCNQD1BWP7T \shift_reg_reg[12] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[11]), .E (n_20), .Q (shift_reg[12]));
  EDFCNQD1BWP7T \shift_reg_reg[9] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[8]), .E (n_20), .Q (shift_reg[9]));
  EDFCNQD1BWP7T \shift_reg_reg[7] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[6]), .E (n_20), .Q (shift_reg[7]));
  EDFCNQD1BWP7T \shift_reg_reg[8] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[7]), .E (n_20), .Q (shift_reg[8]));
  EDFCNQD1BWP7T \shift_reg_reg[3] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[2]), .E (n_20), .Q (shift_reg[3]));
  EDFCNQD1BWP7T \shift_reg_reg[6] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[5]), .E (n_20), .Q (shift_reg[6]));
  MUX4ND0BWP7T g3446__5107(.I0 (tx_buffer[7]), .I1 (tx_buffer[5]), .I2
       (tx_buffer[6]), .I3 (tx_buffer[4]), .S0 (bit_count[1]), .S1
       (bit_count[0]), .ZN (n_13));
  AN2D1BWP7T g3460__6260(.A1 (n_12), .A2 (bit_count[0]), .Z (n_19));
  MOAI22D0BWP7T g3433__4319(.A1 (n_10), .A2 (bit_count[2]), .B1 (n_10),
       .B2 (bit_count[2]), .ZN (n_11));
  OA21D0BWP7T g3461__8428(.A1 (bit_count[0]), .A2 (bit_count[1]), .B
       (n_10), .Z (n_8));
  AOI22D0BWP7T g3462__5526(.A1 (n_9), .A2 (tx_buffer[3]), .B1
       (bit_count[0]), .B2 (tx_buffer[2]), .ZN (n_7));
  INR4D0BWP7T g3458__6783(.A1 (shift_reg[14]), .B1 (shift_reg[10]), .B2
       (shift_reg[11]), .B3 (shift_reg[12]), .ZN (n_6));
  INR2D1BWP7T g3466__3680(.A1 (bit_count[1]), .B1 (n_4), .ZN (n_12));
  ND2D1BWP7T g3467__1617(.A1 (n_3), .A2 (n_2), .ZN (n_14));
  NR2D0BWP7T g3468__2802(.A1 (n_1), .A2 (CS), .ZN (n_32));
  ND2D0BWP7T g3464__1705(.A1 (bit_count[0]), .A2 (bit_count[1]), .ZN
       (n_10));
  NR2XD0BWP7T g3465__5122(.A1 (bit_count[4]), .A2 (CS), .ZN (n_20));
  INVD0BWP7T g3473(.I (RST_N), .ZN (n_1));
  CKND1BWP7T g3470(.I (bit_count[2]), .ZN (n_4));
  CKND1BWP7T g3475(.I (MOSI), .ZN (n_2));
  DFCND1BWP7T \bit_count_reg[4] (.CDN (n_32), .CP (SCLK), .D (n_24), .Q
       (bit_count[4]), .QN (n_17));
  EDFCND1BWP7T \shift_reg_reg[1] (.CDN (RST_N), .CP (SCLK), .D
       (shift_reg[0]), .E (n_20), .Q (shift_reg[1]), .QN (n_0));
  EDFCND1BWP7T \shift_reg_reg[0] (.CDN (RST_N), .CP (SCLK), .D (MOSI),
       .E (n_20), .Q (shift_reg[0]), .QN (n_3));
  EDFCND1BWP7T \bit_count_reg[0] (.CDN (n_32), .CP (SCLK), .D (n_9), .E
       (n_17), .Q (bit_count[0]), .QN (n_9));
  INR3D0BWP7T g2(.A1 (n_20), .B1 (n_27), .B2 (bit_count[3]), .ZN
       (n_84));
endmodule
